"""Add ocr_raw_question and ocr_raw_answer fields

Revision ID: 6f4058347e5f
Revises: 002
Create Date: 2025-11-14 06:37:31.993381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f4058347e5f'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVED: system_configs table operations (should not be deleted)
    # op.drop_index('ix_system_configs_id', table_name='system_configs')
    # op.drop_index('ix_system_configs_key', table_name='system_configs')
    # op.drop_table('system_configs')
    op.add_column('questions', sa.Column('ocr_raw_question', sa.Text(), nullable=True, comment='Raw OCR result from MinerU (read-only, for reference)'))
    op.add_column('questions', sa.Column('ocr_raw_answer', sa.Text(), nullable=True, comment='Raw OCR answer from MinerU (read-only, for reference)'))
    op.alter_column('questions', 'draft_original_question',
               existing_type=sa.TEXT(),
               comment='Editable draft question in Markdown',
               existing_comment='Draft original question in Markdown from MinerU',
               existing_nullable=True)
    op.alter_column('questions', 'draft_original_answer',
               existing_type=sa.TEXT(),
               comment='Editable draft answer in Markdown',
               existing_comment='Draft original answer in Markdown from MinerU',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('ADMIN', 'QUESTION_SUBMITTER', 'OCR_EDITOR', 'OCR_REVIEWER', 'REWRITE_EDITOR', 'REWRITE_REVIEWER', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'QUESTION_SUBMITTER', 'OCR_EDITOR', 'OCR_REVIEWER', 'REWRITE_EDITOR', 'REWRITE_REVIEWER', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('questions', 'draft_original_answer',
               existing_type=sa.TEXT(),
               comment='Draft original answer in Markdown from MinerU',
               existing_comment='Editable draft answer in Markdown',
               existing_nullable=True)
    op.alter_column('questions', 'draft_original_question',
               existing_type=sa.TEXT(),
               comment='Draft original question in Markdown from MinerU',
               existing_comment='Editable draft question in Markdown',
               existing_nullable=True)
    op.drop_column('questions', 'ocr_raw_answer')
    op.drop_column('questions', 'ocr_raw_question')
    # REMOVED: system_configs table recreation (should not be recreated on downgrade)
    # op.create_table('system_configs', ...)
    # op.create_index('ix_system_configs_key', 'system_configs', ['key'], unique=True)
    # op.create_index('ix_system_configs_id', 'system_configs', ['id'], unique=False)
    # ### end Alembic commands ###
